AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My lambda function to be connected with a react app!
Globals:
  Function:
    Timeout: 15
Parameters:
  STAGE:
    Type: String
    Default: dev
  DynamoDB:
    Type: String
    Default: FeedbackDB
Resources:
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref STAGE
  GetFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-getFeedbackLambda
      CodeUri: feedback/
      Environment:
        Variables:
          DynamoTable: !Ref MyDynamoDBTable
          DynamoTableARN: !GetAtt MyDynamoDBTable.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyDynamoDBTable
      Handler: app.getFeedback
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        GetFeedback:
          Type: Api
          Properties:
            Path: /feedback
            Method: GET
            RestApiId: !Ref MyApiGateway
  PostFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-postFeedbackLambda
      CodeUri: feedback/
      Handler: app.postFeedback
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        PostFeedback:
          Type: Api
          Properties:
            Path: /feedback
            Method: POST
            RestApiId: !Ref MyApiGateway
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDB
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  MyApiGateway:
    Description: API Gateway endpoint URL for Prod stage for Feedback function
    Value: !Sub https://${MyApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${STAGE}/feedback/
  GetFeedbackFunction:
    Description: GET Feedback Lambda Function ARN
    Value: !GetAtt GetFeedbackFunction.Arn
  PostFeedbackFunction:
    Description: POST Feedback Lambda Function ARN
    Value: !GetAtt PostFeedbackFunction.Arn
  MyDynamoDBTable:
    Description: DynamoDB table ARN
    Value: !GetAtt MyDynamoDBTable.Arn