AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My lambda function to be connected with a react app!
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
  GetFeedbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${AWS::StackName}-getFeedbackLambda
      CodeUri: feedback/
      Handler: app.getFeedback
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GetFeedback:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /feedback
            Method: GET
            RestApiId: !Ref MyApiGateway
  PostFeedbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${AWS::StackName}-postFeedbackLambda
      CodeUri: feedback/
      Handler: app.postFeedback
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        PostFeedback:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /feedback
            Method: POST
            RestApiId: !Ref MyApiGateway
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyApiGateway:
    Description: "API Gateway endpoint URL for Prod stage for Feedback function"
    Value: !Sub "https://${MyApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/feedback/"
  GetFeedbackFunction:
    Description: "GET Feedback Lambda Function ARN"
    Value: !GetAtt GetFeedbackFunction.Arn
  PostFeedbackFunction:
    Description: "POST Feedback Lambda Function ARN"
    Value: !GetAtt PostFeedbackFunction.Arn
